version: '3.9'

services:
  backend:
    build: ./english_assistant
    ports:
      - "8000:8000"
    volumes:
      - ./english_assistant/app:/app
      - ./english_assistant/models:/app/models
    networks:
      - english_net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000/analyze
    networks:
      - english_net

networks:
  english_net:
    driver: bridge
